// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
// ignore: depend_on_referenced_packages
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__bu4az3xdkbRDh258fJ0ukbbSkbzUyE',
    appId: '1:89062824254:web:0d3bdab3287c0ebb33b46f',
    messagingSenderId: '89062824254',
    projectId: 'notification-45f10',
    authDomain: 'notification-45f10.firebaseapp.com',
    storageBucket: 'notification-45f10.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaUnRHsYmG6cGXd1BxjRh3BWvt8rQSjs0',
    appId: '1:89062824254:android:caaebc29eff62cc133b46f',
    messagingSenderId: '89062824254',
    projectId: 'notification-45f10',
    storageBucket: 'notification-45f10.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI0nhgGakvcWzc89kLP7eJ_d3srPxaP3U',
    appId: '1:89062824254:ios:7e9681983f178c5633b46f',
    messagingSenderId: '89062824254',
    projectId: 'notification-45f10',
    storageBucket: 'notification-45f10.appspot.com',
    iosClientId:
        '89062824254-trugdavughmtdcnmqsagtqa1kb5q5kop.apps.googleusercontent.com',
    iosBundleId: 'com.aditya.testnotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAI0nhgGakvcWzc89kLP7eJ_d3srPxaP3U',
    appId: '1:89062824254:ios:7e9681983f178c5633b46f',
    messagingSenderId: '89062824254',
    projectId: 'notification-45f10',
    storageBucket: 'notification-45f10.appspot.com',
    iosClientId:
        '89062824254-trugdavughmtdcnmqsagtqa1kb5q5kop.apps.googleusercontent.com',
    iosBundleId: 'com.aditya.testnotification',
  );
}
